/**
  * 所有的Token，标识码和名称
  */
object Token extends Enumeration{
	type Token = Value
	//关键字
	val AND = Value(1, "and")
	val ARRAY = Value(2, "array")
	val BEGIN = Value(3, "begin")
	val CALL = Value(4, "call")
	val CASE = Value(5, "case")
	val CHAR = Value(6, "char")
	val CONSTANT = Value(7, "constant")
	val DO = Value(8, "do")
	val ELSE = Value(9, "else")
	val END = Value(10, "end")
	val FOR = Value(11, "for")
	val IF = Value(12, "if")
	val INPUT = Value(13, "input")
	val INTEGER = Value(14, "integer")
	val NOT = Value(15, "not")
	val OF = Value(16, "of")
	val OR = Value(17, "or")
	val OUTPUT = Value(18, "output")
	val PROCEDURE = Value(19, "procedure")
	val PROGRAM = Value(20, "program")
	val READ = Value(21, "read")
	val REAL = Value(22, "real")
	val REPEAT = Value(23, "repeat")
	val SET = Value(24, "set")
	val THEN = Value(25, "then")
	val TO = Value(26, "to")
	val UNTIL = Value(27, "until")
	val VAR = Value(28, "var")
	val WHILE = Value(29, "while")
	val WRITE = Value(30, "write")
	//标识符
	val IDENT = Value(34)
	val INTCONSTANT = Value(36)
	val STRINGCONSTANT = Value(38)
	//单界符号
	val PLUS = Value(39, "+")
	val SUB = Value(40, "-")
	val STAR = Value(41, "*")
	val SLASH = Value(42, "/")
	val EQ = Value(43, "=")
	val GT = Value(44, ">")
	val LT = Value(45, "<")
	val LPAREN = Value(46, "(")
	val RPAREN = Value(47, ")")
	val LBRACKET = Value(48, "[")
	val RBRACKET = Value(49, "]")
	val COLON = Value(50, ":")
	val DOT = Value(51, ".")
	val SEMI = Value(52, ";")
	val COMMA = Value(53, ",")
	//双界符号
	val NEQ = Value(54, "<>")
	val LTEQ = Value(55, "<=")
	val GTEQ = Value(56, ">=")
	val ASS = Value(57, ":=")
	val DDOT = Value(58, "..")
	val LNOTE = Value(59, "/*")
	val RNOTE = Value(60, "*/")
}
